#!/usr/bin/env python3
"""Brands the fork as hottyterm: one generated commit on top of patches/.

    scripts/brand.py [--dry-run] [fork dir]      # default: ../ghostty

The branding is data (brand/brand.toml, brand/icons, brand/overlay). This
script drops the fork's previous branding commit, applies the data to the
tree, checks that no user-facing "Ghostty" is left in the places the check
lists, and commits. Because the commit is regenerated rather than rebased,
upstream changes never conflict with it: at worst an anchor in brand.toml
moved, and this script names it.
"""
import fnmatch
import os
import re
import shutil
import subprocess
import sys
import tomllib

SUBJECT = "hottyterm: branding (generated by scripts/brand.py)"

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BRAND = os.path.join(HERE, "brand")


def git(fork, *args, check=True):
    return subprocess.run(["git", "-C", fork, *args], check=check, capture_output=True, text=True).stdout


def fail(msg):
    sys.exit(f"brand: {msg}")


def fill(s, ident):
    for k, v in ident.items():
        s = s.replace(f"@{k}@", v)
    return s


def files(fork, globs):
    out = set()
    for pattern in globs:
        if not any(ch in pattern for ch in "*?["):
            if os.path.isfile(os.path.join(fork, pattern)):
                out.add(pattern)
            continue
        for root, dirs, names in os.walk(fork):
            dirs[:] = [d for d in dirs if d not in (".git", ".zig-cache", "zig-out")]
            for n in names:
                rel = os.path.relpath(os.path.join(root, n), fork)
                if fnmatch.fnmatch(rel, pattern):
                    out.add(rel)
    return sorted(out)


def drop_previous(fork):
    """Leaves the fork at patches/ only: no branding commit anywhere."""
    if git(fork, "status", "--porcelain").strip():
        fail(f"{fork} has uncommitted changes; commit or discard them first")
    ref = open(os.path.join(HERE, "ghostty-ref")).read().split()[0]
    log = git(fork, "log", "--format=%H %s", f"{ref}..HEAD", check=False).splitlines()
    marks = [line.split(" ", 1)[0] for line in log if line.split(" ", 1)[1] == SUBJECT]
    if not marks:
        return
    if len(marks) > 1:
        fail("more than one branding commit on the branch; drop them by hand")
    mark = marks[0]
    if git(fork, "rev-parse", "HEAD").strip() == mark:
        git(fork, "reset", "-q", "--hard", "HEAD~1")
    else:
        # Commits were made on top of the branding: replay them without it.
        r = subprocess.run(["git", "-C", fork, "rebase", "-q", "--onto", f"{mark}~1", mark], capture_output=True, text=True)
        if r.returncode != 0:
            fail("replaying commits made on top of the branding conflicted; resolve in the fork "
                 "(git rebase --continue), then run this again\n" + r.stdout + r.stderr)


def apply(fork, cfg):
    ident = cfg["identity"]
    changed = set()

    # Images.
    for c in cfg.get("copy", []):
        for n in c.get("sizes", [None]):
            src = os.path.join(BRAND, c["from"].format(n=n))
            if not os.path.exists(src):
                fail(f"missing {src}: run scripts/brand-icons.sh")
            for pattern in c["to"]:
                targets = files(fork, [pattern.format(n=n)])
                if not targets:
                    fail(f"{pattern.format(n=n)}: matches nothing; upstream moved or removed it")
                for rel in targets:
                    shutil.copyfile(src, os.path.join(fork, rel))
                    changed.add(rel)

    # Overlays.
    overlay = os.path.join(BRAND, "overlay")
    for root, _, names in os.walk(overlay):
        for n in names:
            rel = os.path.relpath(os.path.join(root, n), overlay)
            if not os.path.exists(os.path.join(fork, rel)):
                fail(f"overlay {rel} replaces nothing: upstream moved or removed it")
            shutil.copyfile(os.path.join(root, n), os.path.join(fork, rel))
            changed.add(rel)

    # Anchored replacements.
    for rule in cfg.get("replace", []):
        path = os.path.join(fork, rule["file"])
        if not os.path.exists(path):
            fail(f"{rule['file']}: file is gone (rule {rule['from']!r})")
        text = open(path, encoding="utf-8").read()
        n = text.count(rule["from"])
        want = rule.get("count", 1)
        if (want == "any" and n == 0) or (want != "any" and n != want):
            fail(f"{rule['file']}: {rule['from']!r} found {n} time(s), expected {want}")
        open(path, "w", encoding="utf-8").write(text.replace(rule["from"], fill(rule["to"], ident)))
        changed.add(rule["file"])

    # User-facing strings, without anchors.
    for st in cfg.get("strings", []):
        literal = re.compile(st["literal"])
        word = re.compile(st.get("word", r"\bGhostty\b"))
        for rel in files(fork, st["globs"]):
            path = os.path.join(fork, rel)
            text = open(path, encoding="utf-8").read()
            new = literal.sub(lambda m: m.group(1) + word.sub(ident["name"], m.group(2)) + m.group(3), text)
            if new != text:
                open(path, "w", encoding="utf-8").write(new)
                changed.add(rel)

    # The same strings in the translations.
    po = cfg.get("po")
    if po:
        word = re.compile(rf"\b{re.escape(po['word'])}\b")
        for rel in files(fork, po["globs"]):
            path = os.path.join(fork, rel)
            lines = open(path, encoding="utf-8").read().split("\n")
            new = [word.sub(ident["name"], l) if l.startswith(("msgid", "msgstr", '"')) else l for l in lines]
            if new != lines:
                open(path, "w", encoding="utf-8").write("\n".join(new))
                changed.add(rel)
    return changed


def check(fork, cfg):
    left = []
    for c in cfg["check"]:
        left += check_one(fork, c)
    return left


def check_one(fork, c):
    pats = [re.compile(p, re.M) for p in c["patterns"]]
    allow = [re.compile(a) for a in c["allow"]]
    exts = tuple(c.get("exts", ()))
    left = []
    for p in c["paths"]:
        full = os.path.join(fork, p)
        paths = [full] if os.path.isfile(full) else [os.path.join(r, n) for r, _, ns in os.walk(full) for n in ns]
        for path in sorted(paths):
            if exts and not path.endswith(exts):
                continue
            try:
                lines = open(path, encoding="utf-8").read().split("\n")
            except UnicodeDecodeError:
                continue
            for i, line in enumerate(lines, 1):
                if any(pt.search(line) for pt in pats) and not any(a.search(line) for a in allow):
                    left.append(f"  {os.path.relpath(path, fork)}:{i}: {line.strip()[:110]}")
    return left


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    dry = "--dry-run" in sys.argv
    fork = os.path.abspath(args[0] if args else os.environ.get("HOTTYTERM_GHOSTTY", os.path.join(os.path.dirname(HERE), "ghostty")))
    cfg = tomllib.load(open(os.path.join(BRAND, "brand.toml"), "rb"))

    drop_previous(fork)
    changed = apply(fork, cfg)
    left = check(fork, cfg)
    if left:
        git(fork, "checkout", "-q", "--", ".")
        fail("upstream's name or id is still user-facing here (add a rule to brand/brand.toml):\n" + "\n".join(left))
    if dry:
        print(f"brand: {len(changed)} file(s) would change; the check passes")
        git(fork, "checkout", "-q", "--", ".")
        return
    git(fork, "add", "-A")
    git(fork, "commit", "-q", "-m", SUBJECT, "-m",
        "Generated from brand/ in neuroplastio/hottyterm. Do not edit or export;\n"
        "scripts/brand.py drops and regenerates it.")
    print(f"brand: {len(changed)} file(s) branded as {cfg['identity']['name']} "
          f"({git(fork, 'rev-parse', '--short', 'HEAD').strip()})")


if __name__ == "__main__":
    main()
