#!/bin/sh
# Writes the fork's commits since ghostty-ref back to patches/, replacing
# what is there, without the generated branding commit (scripts/brand.py).
# Run after every change to the fork.
#
#   scripts/export.sh
set -eu
HERE="$(cd "$(dirname "$0")/.." && pwd)"
FORK="${HOTTYTERM_GHOSTTY:-$(dirname "$HERE")/ghostty}"
REV="$(grep -v '^#' "$HERE/ghostty-ref" | head -1)"
BRAND="hottyterm: branding (generated by scripts/brand.py)"
TOP=hottyterm
[ "$(git -C "$FORK" log -1 --format=%s "$TOP")" = "$BRAND" ] && TOP="hottyterm~1"
if git -C "$FORK" log --format=%s "$REV..$TOP" | grep -qxF "$BRAND"; then
  echo "commits sit on top of the branding: run scripts/brand.py first (it moves the branding to the top)" >&2
  exit 1
fi
rm -f "$HERE"/patches/*.patch
git -C "$FORK" format-patch -q --no-signature --zero-commit -o "$HERE/patches" "$REV..$TOP"
ls "$HERE"/patches
